### ISSUE TITLE
Docs do not match what the UI says in the case of Identity Management docs

### ISSUE THREAD

**Issue by cfoskin** [aerogear/mobile-docs#110]
The provisioning guide says choose the Identity management service in the catalog https://github.com/aerogear/mobile-docs/blob/master/modules/ROOT/pages/keycloak/provisioning.adoc
 But the UI we have Keycloak:

![screen shot 2018-06-25 at 15 06 26](https://user-images.githubusercontent.com/7661017/41854978-681a5532-7889-11e8-8e20-ef41db5b1e6b.png)

This can be confusing for the user

**Comment by finp** [comment]
being actioned by jason
