### ISSUE TITLE
Create a GitHub issue template for this repo

### ISSUE THREAD

**Issue by davidffrench** [aerogear/mobile-docs#218]
It would be nice to have a GitHub issue template for what makes sense on this repo. The same as what the mobile-core repo uses - https://github.com/aerogear/mobile-core/issues/new

**Comment by laurafitzgerald** [comment]
@davidffrench That's a good suggestion. I'll create a pr to add this as it's valuable to today's exercies

**Comment by laurafitzgerald** [comment]
@finp what types of info would you see as being valuable when contributors create an issue?

**Comment by pmacko1** [comment]
@laurafitzgerald should we close this?

**Comment by laurafitzgerald** [comment]
yes, the pr is merged
