### ISSUE TITLE
Explanation for what a binding is in Docs before saying not to choose "choose Do not bind at this time"

### ISSUE THREAD

**Issue by Nanyte25** [aerogear/mobile-docs#219]
We need to explain to a user what a binding is before we tell them not to choose an option
<img width="1044" alt="step 5 of tutorial" src="https://user-images.githubusercontent.com/9899691/42622931-76fcbc6a-85b9-11e8-978c-3b4b1bbac36f.png">
?.

**Comment by Nanyte25** [comment]
I see that this is explained further down in  the docs https://docs.aerogear.org/aerogear/latest/getting-started.html#prerequisites  under "Binding a Mobile Client"

**Comment by finp** [comment]
not explaining binding at this time is an editorial choice as per https://github.com/aerogear/mobile-docs/issues/239
