### ISSUE TITLE
requirement for no errors running 'oc cluster up'

### ISSUE THREAD

**Issue by mmurphy** [aerogear/mobile-docs#224]
the note in the pre requisites requiring the ability to run ```oc cluster up``` with no errors does not specify whether ```WARNINGS``` are ok or not.
I received warnings:

> WARNING: Port 80 is already in use and may cause routing issues for applications.
> WARNING: Port 443 is already in use and may cause routing issues for applications.

and

> WARNING: An HTTP proxy (docker.for.mac.http.internal:3128) is configured for the Docker daemon, but you did not specify one for cluster up
> WARNING: An HTTPS proxy (docker.for.mac.http.internal:3129) is configured for the Docker daemon, but you did not specify one for cluster up
> WARNING: A proxy is configured for Docker, however 172.30.1.1 is not included in its NO_PROXY list.
>    172.30.1.1 needs to be included in the Docker daemon's NO_PROXY environment variable so pushes to the local OpenShift registry can succeed.

and I'm unclear whether this is ok or not

**Comment by finp** [comment]
Openshift issue, will not be addressed for mobile services docs
