### ISSUE TITLE
No issue template in mobile-docs repo if I am filing an issue

### ISSUE THREAD

**Issue by damienomurchu** [aerogear/mobile-docs#225]
When I file an issue in other aerogear repos, like mobile-core, I get an [issue template](https://github.com/aerogear/mobile-core/blob/master/.github/PULL_REQUEST_TEMPLATE.md) when I am filing an issue. A similar template could be added to mobile-docs for an docs issues raised

**Comment by laurafitzgerald** [comment]
[PR](https://github.com/aerogear/mobile-docs/pull/222) created. @damienomurchu feel free to make suggestions in terms of sections you would think make sense in an issue template

**Comment by laurafitzgerald** [comment]
also closing in favor of this [issue](https://github.com/aerogear/mobile-docs/issues/218)
