### ISSUE TITLE
in the "Configuring the Service" section of the Doc's

### ISSUE THREAD

**Issue by Nanyte25** [aerogear/mobile-docs#226]
We need some extra steps under "Configuring keycloak" https://docs.aerogear.org/aerogear/latest/getting-started.html#prerequisites

Open Clients from the menu.

Open your client. The name of your client is derived from the name of the Mobile Client, the name of the mobile development platform and the client type, for example myapp-android-public.

User needs to click into "myapp-android-public" under "Client ID's"

Add <schema>:/callback to Valid Redirect URIs.
take the example schem and use it in the case of android?

Add com.aerogear.androidshowcase:/callback to Valid Redirect URIs?

Add <schema> to Web Origins.

**Comment by finp** [comment]
. Open your client. The name of your client is derived from the name of the Mobile Client, the name of the mobile development platform and the client type, for example myapp-android-public.

. Select the client, for example, click myapp-android-public.

. Add <schema>:/callback to Valid Redirect URIs. For example, if you are using Android, com.aerogear.androidshowcase:/callback

. Add <schema> to Web Origins. For example, if you are using iOS, org.aerogear.ios-showcase-template

. Save your changes.
