### ISSUE TITLE
installation - dockerhub defaults confusing - suggest re-ordering description

### ISSUE THREAD

**Issue by mmurphy** [aerogear/mobile-docs#228]
step 4 in the installation procedure lists defaults for dockerhub
however as I am going through the install process I have questions about the default values.
It turns out that they are described after the box listing the defaults.  I think it would be useful if either the description was before the box, or if it mentioned that they would be described afterwards

**Comment by finp** [comment]
@mmurphy  I'm not sure what you mean:
1. Enter your Docker Hub login credentials when prompted. The installer checks these credentials are valid before continuing.
2. Accept the default values for the next set of prompts

The idea is that you accept the 4 prompts below (unless you know what to change them to, ie expert user). Not sure how to improve that

**Comment by finp** [comment]
agreed, but needs more rewording to make it work, @jstaffor ?

**Comment by jstaffor** [comment]
https://github.com/aerogear/mobile-docs/pull/314/
