### ISSUE TITLE
installation - self signed cert

### ISSUE THREAD

**Issue by mmurphy** [aerogear/mobile-docs#229]
step 5 says to verify the installation:

> Open a browser and login (accepting the self-signed certificate):

However the pre-reqs say that ```oc cluster up``` should work.
to verify it worked, I browsed to openshift console and accepted the self-signed cert.
So, if it's required to call out the self-signed cert here, it should also be called out above in the pre-reqs.

**Comment by finp** [comment]
seems to be an issue that would best be addressed in openshift docs
leaving the instruction here helps the less diligent user (who hasn't actually run oc cluster up)
