### ISSUE TITLE
Getting Started > Prerequisites - Ansible version specified >= 2.4 but installer requires >=2.6

### ISSUE THREAD

**Issue by davidffrench** [aerogear/mobile-docs#230]
Mismatch between docs and installer on required Ansible version

**Docs Link:** https://docs.aerogear.org/aerogear/latest/getting-started.html#prerequisites
**Docs Ansible:** >=2.4
**Installer Ansible:** >=2.6

![2018-07-12_10-32-38](https://user-images.githubusercontent.com/1596014/42625228-21d4f8dc-85bf-11e8-989f-64c03b77c0ff.png)
![2018-07-12_10-32-13](https://user-images.githubusercontent.com/1596014/42625231-268866f2-85bf-11e8-82b6-03f7b81c7b94.png)

**Comment by jasonmadigan** [comment]
Resolved in https://github.com/aerogear/mobile-docs/pull/227
