### ISSUE TITLE
installation - there are warning and failed messages displayed

### ISSUE THREAD

**Issue by mmurphy** [aerogear/mobile-docs#231]
the installer displays WARNING and FAILED messages
I think it might be a good idea to call out that these are expected and that once the resulting output-oc-cluster-status: debug message is displayed then everything is ok

**Comment by finp** [comment]
We do document the output of  a typical  successful install. That's the trigger to continue, which is what we want the user to do.
We could add something like:
"Warnings and  errors are displayed, ignore these", but I feel that this is dangerous ground... A sophisticated user should review these, and a novice user should ignore them. 
If you have a suggestion how to word this, reopen

**Comment by mmurphy** [comment]
How about changing the text

> The following installation can take a while the first time it runs, as it pulls a number of Docker images. Once completed successfully, this results in an output similar to the following:

to

> The following installation can take a while the first time it runs, as it pulls a number of Docker images. Once output similar to the following is displayed it indicates that it has completed successfully and you can proceed.

**Comment by finp** [comment]
+1 to suggestion above

**Comment by jstaffor** [comment]
https://github.com/aerogear/mobile-docs/pull/319
