### ISSUE TITLE
issue with Openshift admin login details.

### ISSUE THREAD

**Issue by Nanyte25** [aerogear/mobile-docs#232]
in this section of the doc's "Using Self-Signed Certificates in Mobile Apps"

1. Extracting the OpenShift Root Certificate Authority Cert
Log into OpenShift as the admin user.

A user who has never use Openshift before would need to know what the default admin login is ?

```
oc login -u system:admin
Logged into "https://10.32.246.176:8443" as "system:admin" using existing credentials.

```

**Comment by finp** [comment]
fixed in #265
