### ISSUE TITLE
installation - verification console url is incorrect

### ISSUE THREAD

**Issue by mmurphy** [aerogear/mobile-docs#233]
verification step says to browse to

> https://192.168.37.1:8443/console/

The URL is incorrect, it should be the URL displayed by the installer as the "Web console URL"

**Comment by davidffrench** [comment]
Came across the same issue.

**Comment by finp** [comment]
@pmacko1  change step 5:
5. Verify the installation:
Open a browser and login (accepting the self-signed certificate):
https://192.168.37.1:8443/console/

to:
5. Verify the installation:
Browse to the Web console URL displayed at the end of the installation, and log in, accepting the self-signed certificate if displayed.

**Comment by jstaffor** [comment]
https://github.com/aerogear/mobile-docs/pull/304
