### ISSUE TITLE
installation - end of installation step

### ISSUE THREAD

**Issue by mmurphy** [aerogear/mobile-docs#234]
while the last text in the install step says

> At the top of the catalog package, find the Mobile category that indicates that the mobile features of AeroGear Mobile Services are succesfully installed.

I think that it would be a good idea, to call out that once you can see the tab the installation is done.
To me the action of the current text is for me to find the category, I was then expecting to have to do something after finding it.  So maybe something like 'once you can see the Mobile tab, mobile services are installed and you can proceed to registering a mobile client'

**Comment by finp** [comment]
This is already in a step 'Verify the installation', and says ' that indicates that the mobile features of AeroGear Mobile Services are succesfully installed' but the wording isn't  great, suggestion:

end of a.
The service catalog is displayed.

b. Check that the *Mobile* tab is displayed in the service catalog. If this tab is not displayed, wait a few minutes to make sure that the installation process has completed. If the *Mobile* tab still is not displayed, follow the troubleshooting steps below.

**Comment by jstaffor** [comment]
https://github.com/aerogear/mobile-docs/pull/340
