### ISSUE TITLE
installation - registering a mobile client

### ISSUE THREAD

**Issue by mmurphy** [aerogear/mobile-docs#235]
after installing Aerogear Mobile Services in my OpenShift,
the register a mobile client goes on to say

> A Mobile Client in OpenShift is a representation of the mobile app ...

should this be referring to a Mobile Client in Aerogear Mobile Services, or a Mobile Client in Openshift that has had the Aerogear mobile Services installed, or is it really a mobile client in Openshift?

**Comment by finp** [comment]
"a Mobile Client in Openshift that has not had the Aerogear mobile Services installed" is not possible
This is an ongoing terminology discussion, raise on ML to continue that discussion
