### ISSUE TITLE
[getting started] Registering a mobile client

### ISSUE THREAD

**Issue by mmurphy** [aerogear/mobile-docs#237]
## Description
```
> The Mobile Client view displays a list of mobile services that you can associate with the Mobile Client, and offers to provision any mobile service that is in the service catalog but is not currently provisioned.

it shows me 1 provisioned service - the app that I specified in the previous step.
It is not clear if this is "associated", it lists it as "provisioned"
There is also no offer to provision other mobile services.  If I expand the  Mobile Client I created there is a button for "Browse Mobile Services"
```
## Link to Page/Section where Issue was seen
https://docs.aerogear.org/aerogear/latest/getting-started.html#registering

## Suggested edit
from @pmacko1: 
- you can't really provision anything but mobile ci/cd from the mobile client overview, if there is already at least one service provisioned (if not, there is a "Browse Mobile Services" button)
- I don't see any value in dissecting this any further, my suggestion is to remove the whole paragraph.

**Comment by finp** [comment]
The UI is still in flux, will address when I can test myself

**Comment by pmacko1** [comment]
@mmurphy hi, i updated this issue, do you mind taking a look? thanks!

**Comment by finp** [comment]
@pmacko1 can you set up a meeting with a demo environment so that we can review this?

**Comment by pmacko1** [comment]
@finp, hi, https://master.pmacko.openshiftworkshop.com/console/catalog . Use credentials from openshift workshop tutorial

**Comment by pmacko1** [comment]
this will become out-of-date because of the mobile dev console

**Comment by finp** [comment]
closing as out of date
