### ISSUE TITLE
Getting Started Prerequisites Listed too late in process

### ISSUE THREAD

**Issue by jmernin** [aerogear/mobile-docs#242]
When working my way through the Getting Started Guide [1], one of the first things I did was to switch to the OpenShift setup/installation guide [2]. When trying to install OpenShift, I hit a number of package dependency (or versioning) issues (e.g. older version of Ansible) that I might not have had if I'd satisfied all of the prerequisites first.

I therefore recommend that we put our Prerequisites *before* anything else in the docs.

[1] https://docs.aerogear.org/aerogear/latest/getting-started.html
[2] https://www.openshift.org/

**Comment by finp** [comment]
this seems to be resolved by a previous PR
