### ISSUE TITLE
Step 3 on binding a mobile client needs a warning to wait

### ISSUE THREAD

**Issue by austincunningham** [aerogear/mobile-docs#243]
step 3 on https://docs.aerogear.org/aerogear/latest/getting-started.html#binding, It can take some time for the mobile services tab to show up , needs a warning , also wouldn't call it a tab its a link `view all mobile services`

![image](https://user-images.githubusercontent.com/16667688/42628274-8c98a2ce-85c7-11e8-961c-c102747745fa.png)

**Comment by maleck13** [comment]
No they are tabs, I think @austincunningham is referring to the link on the overview page.

There shouldn't be delays no

**Comment by finp** [comment]
@austincunningham  I think you didn't navigate to {mobile-client} screens as per step 2. Instead you expanded the mobile client.
If you had navigated to the mobile client screen, you'd have the option to select the Mobile Services tab. 
Reopen if you think this still needs to be addressed
