### ISSUE TITLE
[identity, binding] Getting Started - Binding a Mobile Client

### ISSUE THREAD

**Issue by mmurphy** [aerogear/mobile-docs#244]
steps 5 and 6 should be sub steps of 4

Step 6 "Choose the Keycloak client type." and the following note are confusing.
I would be better to say "choose public as the client type" and afterwards potentially explain the difference between public and bearer.

The note also says 

> When binding to other services you should use client type bearer unless they also need to authenticate.
step 6 says "bearer should be used to bind to services that only need to verify tokens."

how will someone know if other services will also need to authenticate?

**Comment by finp** [comment]
@witmicko  does Martin's suggestion make sense?

**Comment by finp** [comment]
@pmacko1  can you review this?

**Comment by pmacko1** [comment]
@mmurphy @finp I would suggest to avoid explaining Keycloak-specific terminology. Can we remove both steps and point users to keycloak .

We can't do this if this is our construct, though.

**Comment by pmacko1** [comment]
we use this as a module in getting started. I think we need to tell users to use default values for the demonstration(public). wdyt?

**Comment by finp** [comment]
@pmacko1  I'm not sure what you're suggesting, wanna make a PR?

**Comment by pmacko1** [comment]
@finp @mmurphy 
I believe that the current docs try to explain some Keycloak concepts and how do we implement them with Mobile services.
- we want to guide users to set up a working demo app in getting started (click here, click there, done)
- default value is `public`, so stating "use default values" in ^ should imo work if we want to avoid using(explaining) Keycloak terminology.

We want to avoid duplicating docs/explaining concepts that are not our own. That is not always possible/desirable. Are we able to do that here?

**Comment by finp** [comment]
@pmacko1  could you prepare a doc with the suggestion (before and after), then we'll ping @wtrocki  to review

**Comment by pmacko1** [comment]
https://github.com/aerogear/mobile-docs/pull/423 @finp
