### ISSUE TITLE
Installation via Docker Machine approach not supported?

### ISSUE THREAD

**Issue by jmernin** [aerogear/mobile-docs#245]
When working my way through the installation process for OpenShift (as a prerequisite for AMS), I inadvertently chose the "Mac OS X with Docker Machine" method and ran into several issues with that. It seems that is not supported (by AMS) and I should have used the "MacOS with Docker for Mac" method instead.

If it's true that the machine-based method is not supported (or not tested), we should be more explicit about this earlier on (e.g. in our Prerequisites section).

[1] https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#mac-os-x-with-docker-machine
[2] https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#macos-with-docker-for-mac

**Comment by finp** [comment]
@maleck13  any opinions here?

**Comment by finp** [comment]
@jhellar  do you know if anyone tested this?
or should we add:

NOTE: Do not use the "Mac OS X with Docker Machine"  method when running oc cluster up on macOS .

**Comment by jhellar** [comment]
@finp not sure, I haven't tested it. But if there are issues with "Mac OS X with Docker Machine", we should probably say something like: "for macOS make sure to use MacOS with Docker for Mac".

**Comment by finp** [comment]
@jstaffor  update with 

NOTE: Installation on macOS with Docker Machine has not been tested, use the link:https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#macos-with-docker-for-mac[Docker for Mac] instructions when installing OpenShift.

**Comment by jstaffor** [comment]
https://github.com/aerogear/mobile-docs/pull/339
