### ISSUE TITLE
getting started - Configuring the service

### ISSUE THREAD

**Issue by mmurphy** [aerogear/mobile-docs#246]
the first line introduces a lot of new terms, and it is unclear which or if any actually apply to this or why

> The following section will guide you through configuring the schema of the redirect url and web origin for a client in Keycloak. This is required to enable OpenID authentication.

- schema
- redirect url
- web origin
- keycloak (we have previously bound to a identity management service)
- OpenID authentication

For example, it says "This is required to enable OpenID authentication." am I required to use openid?, does it only apply if I want to use openid?,

**Comment by jstaffor** [comment]
https://github.com/aerogear/mobile-docs/pull/338
