### ISSUE TITLE
getting started - configuring the service

### ISSUE THREAD

**Issue by mmurphy** [aerogear/mobile-docs#247]
Step 1 says: 

> Expand the Identity Management Service by clicking the > icon.

However there is no ">" icon on my screen, it is also not in the previous screenshot.

**Comment by finp** [comment]
change from:
2. Select the Mobile Services tab.
3. After the binding is complete, you can expand the Identity Management Service by clicking the > icon.

to:

2. Select the Mobile Services tab. 
3. If a binding to the {keycloak-service} service is in progress,  a spinning icon is displayed to the right of the {keycloak-service} entry. Wait for the binding process to complete.
3. If the *Keycloak Realm URL*  URL is not visible,  expand the Identity Management Service by clicking the > icon.

**Comment by jstaffor** [comment]
https://github.com/aerogear/mobile-docs/issues/247
