### ISSUE TITLE
Not quite sure where the starting point for Configuring the service is ???

### ISSUE THREAD

**Issue by austincunningham** [aerogear/mobile-docs#248]
Where in Openshift should I be to start step 1 in https://docs.aerogear.org/aerogear/latest/getting-started.html#localdev

**Comment by austincunningham** [comment]
Should it include `project\Overview\Provisioned Services` and select the `Identity Management`

**Comment by jstaffor** [comment]
https://github.com/aerogear/mobile-docs/issues/248
