### ISSUE TITLE
Inconsistent choice of tabbed menuing system in some of our docs

### ISSUE THREAD

**Issue by jmernin** [aerogear/mobile-docs#249]
At various points in our docs (e.g. running Running your First Mobile app [1]), we appear to be using a mini tabbed menu to allow people choose between iOS, Android, Cordova and Xamarin.

While I eventually spotted that this was, in fact, a menu (and also eventually noticed that it was consistent with the overall styling of the docs site itself), it was not at all obvious to me on first viewing so maybe we should consider an alternative representation here.

This is not a deal breaker and perhaps nobody else experienced this issue, but I felt it worth noting in any case, per chance it does become a UX issue later on.

[1] https://docs.aerogear.org/aerogear/latest/getting-started.html#running

**Comment by finp** [comment]
NOTE: this styling was worked on quite a bit, this was best effort for now and the asciidoc code is flexible enough to be rendered differently depending on requirements. Closing for now, will revisit if we get more similar feedback
