### ISSUE TITLE
getting started - configuring the service

### ISSUE THREAD

**Issue by mmurphy** [aerogear/mobile-docs#250]
steps 6 and 7
it is not clear that <schema> refers to the schema name referenced above, or if it's the text "<schema>"

Additionally it is not clear if the 2 items should be added as additional URLs or if they should be added to the existing URLS

**Comment by finp** [comment]
1. adding example to make this clearer, handling in https://github.com/aerogear/mobile-docs/issues/226
2. We ask users to 
 Add `<schema>:/callback` to `Valid Redirect URIs`.
@ciaranRoche  can you confirm that we're asking users to add these as additional urls?

**Comment by ciaranRoche** [comment]
Yes, for the `Valid Redirect URIs` we need to add `:/callback` to the `schema`. For the `web origins` it is just the `schema`.
We have an example `schema` in the dialog box above the steps. I believe we wanted to keep the schema example separate to this step to avoid people copy and pasting directly.
