### ISSUE TITLE
Login instructions while setting up self-signed certs are confusing

### ISSUE THREAD

**Issue by jmernin** [aerogear/mobile-docs#251]
The first instruction in the steps to set up your self-signed certs say, "Log into OpenShift as the admin user". Having just followed a number of other instructions in the previous sections, which ask you to log into the OpenShift Console, I mistook this instruction and logged into the console.

However, it turns out this step is actually trying to tell you to log into OpenShift from the command-line, not the console. This should be much clearer.

[1] https://docs.aerogear.org/aerogear/latest/getting-started.html#using-self-signed-certificates-in-mobile-apps

**Comment by finp** [comment]
Text is currently:

Log into OpenShift as the admin user.
$ oc login -u system:admin

@jstaffor  I think we just need a colon:

Log into OpenShift as the admin user:
$ oc login -u system:admin

**Comment by jstaffor** [comment]
https://github.com/aerogear/mobile-docs/pull/331
