### ISSUE TITLE
Step 2 of `Configuring the Service` no Realm url present

### ISSUE THREAD

**Issue by austincunningham** [aerogear/mobile-docs#253]
Step 2 of `Configuring the Service` no Realm url present

![image](https://user-images.githubusercontent.com/16667688/42629185-7a381b34-85ca-11e8-96a8-67d80f7d11b9.png)

**Comment by finp** [comment]
@austincunningham  is this a docs issue? or a bug?

**Comment by austincunningham** [comment]
@finp Its doc's I would say as there is a url present but not in the location the docs describe

**Comment by finp** [comment]
@austincunningham want to make a suggestion here? what can I click to get to Admin ui?

**Comment by finp** [comment]
@aidenkeating  How can we phrase this better:
1. Expand the Identity Management Service by clicking the > icon.
2. Click on the Realm URL link to open the Keycloak Administration Console.

Should we say something like:
1. Navigate to the Keycloak Admin UI by clicking the URL listed to the right of the Identity Management Service name.

**Comment by aidenkeating** [comment]
@finp @austincunningham That suggestion sounds good to me, maybe we should also mention we're referring to the Overview screen here? Something like:

"Navigate to the Keycloak Admin UI by clicking the URL listed to the right of the Identity Management Service name on the OpenShift Overview screen."

**Comment by austincunningham** [comment]
@finp the issue is that the url is nowhere near the `Identity Management Service` it is else where in the openshift console.

**Comment by aidenkeating** [comment]
@austincunningham Going through this section of the document fully I'm not sure I see the issue. The previous section on binding leaves me on the `Mobile Services` tab of the `Mobile Client` screen. Once the binding is complete I click `>` and I see the Realm URL. See below.

@finp I think we could clarify we're still meant to be on the `Mobile Services` tab and the exact key for the URL. Something like (I suck at words):

"On the Mobile Services tab of the Mobile Client screen expand the Identity Management service and click the Keycloak Realm URL"

<img width="1209" alt="screen shot 2018-07-20 at 11 25 35" src="https://user-images.githubusercontent.com/8698527/42997741-ab7412a2-8c0f-11e8-94bc-2ce822d97524.png">

**Comment by finp** [comment]
. Navigate to the {mobile-client} screen.
. Select the Mobile Services tab.
. Expand the Identity Management Service by clicking the > icon.
. Click on the *Keycloak Realm URL* link to open the Keycloak Administration Console.

**Comment by aidenkeating** [comment]
@finp Perhaps we could also add something to the end of the binding section suggesting that this can take some time and the UI will update when the binding is complete?

**Comment by austincunningham** [comment]
@finp 
- From the project screen expand `Identity Management` by clicking the > icon.
- Navigate to the {mobile-client} screen by click on the link provided.
- Expand the Identity Management Service by clicking the > icon.
- Click on the Keycloak Realm URL link to open the Keycloak Administration Console.

**Comment by finp** [comment]
. Navigate to the {mobile-client} screen.
. Select the Mobile Services tab.
. After the binding is complete, you can expand the Identity Management Service by clicking the > icon.
. Click on the Keycloak Realm URL link to open the Keycloak Administration Console.
