### ISSUE TITLE
getting started - setting up your local development environment - missing as a pre-req

### ISSUE THREAD

**Issue by mmurphy** [aerogear/mobile-docs#256]
> ... you will need to have set up a local development environment ...

This should be listed as a pre-requisite

**Comment by pmacko1** [comment]
@mmurphy where do you think this should be?

**Comment by mmurphy** [comment]
@pmacko1 in the list of prerequisites?

**Comment by pmacko1** [comment]
@matskiv

**Comment by mmurphy** [comment]
@pmacko1 Yes, I mean those [prereqs](https://docs.aerogear.org/aerogear/latest/getting-started.html#prerequisites)
You need an IDE before the end of the getting started guide, so I think it should be included at the start to the getting started guide with the other pre-requisites.  I was working through the getting started guide, and near then end found out that I needed Xcode.

**Comment by jstaffor** [comment]
https://github.com/aerogear/mobile-docs/pull/320
