### ISSUE TITLE
Incorrect path quoted for mobile-services.json file

### ISSUE THREAD

**Issue by jmernin** [aerogear/mobile-docs#257]
The instructions for downloading the Mobile Services Configuration file (into the cloned Showcase App repo) [1] are missing the directory "app" from the path to this file. The instructions suggest this file is at:

`src/main/assets/mobile-services.json`

when in fact it's at:

`app/src/main/assets/mobile-services.json`

[1] https://docs.aerogear.org/aerogear/latest/getting-started.html#downloading-the-mobile-services-configuration-file

**Comment by jstaffor** [comment]
https://github.com/aerogear/mobile-docs/pull/290
