### ISSUE TITLE
Hyperlinks that take you away from the main docs should open in a new tab

### ISSUE THREAD

**Issue by jmernin** [aerogear/mobile-docs#258]
When working your way through the full Getting Started Experience, from start to finish, you are diverted away from our docs for large chunks of other setup tasks (some of which have follow-on links to other sites also). It's very easy to get lost here and be unable to find your way back to the AMS docs site.

Therefore, I recommend that any hyperlink that takes you away from the AMS doc open in a separate tab so that you don't lose the flow of where you came from.

**Comment by finp** [comment]
fixed in #302
