### ISSUE TITLE
Which versions of Android are supported?

### ISSUE THREAD

**Issue by jmernin** [aerogear/mobile-docs#259]
When following the instructions to set up Android Studio in order to run my first mobile app in an emulator, I had to make a number of decisions around versions of Android (e.g. 27 or 28). It was not clear to me which of these is (and is not) supported by our current AMS release.

Again, perhaps a mention of this in the Prerequisites section might help, perhaps in the same area where we advise people not to use the Docker Machine-based installer on OSX?

**Comment by finp** [comment]
@aidenkeating  do we have a minimum android level for the android sdk?

**Comment by aidenkeating** [comment]
@finp I believe it's [L/Lollipop](https://source.android.com/setup/start/build-numbers) (API level 21) based on [our SDK](https://github.com/aerogear/aerogear-android-sdk/blob/master/constants.gradle#L4:21), @wei-lee @secondsun can you confirm?

**Comment by wei-lee** [comment]
@aidenkeating Yes, that's right.
