### ISSUE TITLE
Outline the end goal of "Provisioning your first service" at the very beginning

### ISSUE THREAD

**Issue by davidffrench** [aerogear/mobile-docs#261]
It would be great to outline to the reader what the end goal that they will achieve at the start of https://docs.aerogear.org/aerogear/latest/getting-started.html#provisioning.

This could be:
**Goals on completion of this section**
- A basic mobile app running on a device with integrated identity management (keycloack)

**Comment by finp** [comment]
I think this was addressed in https://github.com/aerogear/mobile-docs/pull/318
albeit in the main introduction
