### ISSUE TITLE
step 1a of `using self-signed Certificates in mobile apps` is not clear what or who is the admin user

### ISSUE THREAD

**Issue by austincunningham** [aerogear/mobile-docs#262]
At step 1a. in https://docs.aerogear.org/aerogear/latest/getting-started.html#using-self-signed-certificates-in-mobile-apps it is not clear who the admin user , is it the developer account or are we doing ```oc login -u system:admin -n default```

**Comment by finp** [comment]
system:admin is specifically mentioned now
