### ISSUE TITLE
getting started - Running the Mobile App in an Emulator - missing pre-req cocoa pods for iOS showcase app

### ISSUE THREAD

**Issue by mmurphy** [aerogear/mobile-docs#264]
the  iOS showcase app appears to require cocoa pods , but it is not listed as a pre-req

**Comment by finp** [comment]
@jstaffor  change:

Run this command to install dependencies:

$ pod install

to 

. Install CocoaPods as described in link:https://cocoapods.org/[] if it is not already installed.
. Run this command to install dependencies:
+
----
$ pod install
----

**Comment by jstaffor** [comment]
https://github.com/aerogear/mobile-docs/pull/305
