### ISSUE TITLE
Should be a verification step at the bottom 

### ISSUE THREAD

**Issue by austincunningham** [aerogear/mobile-docs#268]
Should be a verification step at the bottom i.e. when completed you should be able to authenticate

![5x](https://user-images.githubusercontent.com/16667688/42632864-8578ae4e-85d6-11e8-9ea6-732d31e127e1.gif)

**Comment by finp** [comment]
@austincunningham  what are you suggesting?

**Comment by austincunningham** [comment]
@finp there is no steps to verify you have been successful. You have no idea what a successful outcome to the steps is.

**Comment by finp** [comment]
this got added as part of another PR, see last section of https://docs.aerogear.org/aerogear/latest/getting-started.html#building-and-running-the-mobile-app-in-an-emulator
and reopen if nec
