### ISSUE TITLE
Outline at the start that services do not work with a cluster IP of 127.0.0.1

### ISSUE THREAD

**Issue by davidffrench** [aerogear/mobile-docs#270]
Please outline at the start that services do not work with a cluster IP of 127.0.0.1. I was able to run the installer, create a mobile client and begin provisioning an identity management service but this ultimately failed because the cluster IP was set to 127.0.0.1

**Comment by finp** [comment]
@maleck13  It seems that it's possible to end up with a cluster IP of 127.0.0.1, do you know why? perhaps when you lose network connection?
I'd like to avoid documenting edge cases, especially as prereqs. Is this something that oc cluster up doc should handle rather than us?

**Comment by finp** [comment]
no response:
add note under step 4 of https://docs.aerogear.org/aerogear/latest/getting-started.html#procedure

NOTE: If your Cluster IP address is reported as 127.0.0.1, the installation will not succeed. Check your network connection and restart the installer.

**Comment by pmacko1** [comment]
https://github.com/aerogear/mobile-docs/pull/324

**Comment by finp** [comment]
we could add the note as i suggested?

**Comment by pmacko1** [comment]
it is there :) resolved
