### ISSUE TITLE
Not explicit in docs that schema for android app Keycloak redirect url *has* to be android package name 

### ISSUE THREAD

**Issue by damienomurchu** [aerogear/mobile-docs#271]
If schema is not the same as the android app package name, the keycloak authentication will fail with the error `invalid redirect url`. Current doc note: 
`It is recommended to use the package name of the Android app as the schema of the redirect url to avoid conflicts. (e.g. com.aerogear.androidshowcase)`

Screenshots:

![screenshot from 2018-07-12 13-46-38](https://user-images.githubusercontent.com/12085451/42634502-492c8fdc-85db-11e8-9f02-79c86e42418f.png)
![screenshot from 2018-07-12 13-46-26](https://user-images.githubusercontent.com/12085451/42634503-49451e08-85db-11e8-8a31-780757cb2912.png)

**Comment by jstaffor** [comment]
https://github.com/aerogear/mobile-docs/pull/289
