### ISSUE TITLE
FAILED TASK [ansible-service-broker-setup : Execute OpenShift Ansible Broker (OAB) provision script] 

### ISSUE THREAD

**Issue by judyobrienie** [aerogear/mobile-docs#272]
TASK [ansible-service-broker-setup : Execute OpenShift Ansible Broker (OAB) provision script] ********************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "bash -e /tmp/provision-ansible-service-broker.sh \"judyobrien\" \"*******\" \"aerogearcatalog\" \"True\" \"latest\" \"10.201.82.163\" \"nip.io\" \"ansible-service-broker\" \"Always\"", "delta": "0:00:03.067484", "end": "2018-07-12 14:11:35.282793", "msg": "non-zero return code", "rc": 1, "start": "2018-07-12 14:11:32.215309", "stderr": "error: unable to recognize servicecatalog.k8s.io/v1beta1, Kind=ClusterServiceBroker: no matches for servicecatalog.k8s.io/, Kind=ClusterServiceBroker", "stderr_lines": ["error: unable to recognize servicecatalog.k8s.io/v1beta1, Kind=ClusterServiceBroker: no matches for servicecatalog.k8s.io/, Kind=ClusterServiceBroker"], "stdout": "starting install of OpenShift Ansible Broker (OAB)\nLogged into \"https://10.201.82.163:8443\" as \"system:admin\" using existing credentials.\n\nYou have access to the following projects and can switch between them with 'oc project <projectname>':\n\n    default\n    kube-public\n    kube-service-catalog\n    kube-system\n  * myproject\n    openshift\n    openshift-infra\n    openshift-node\n    openshift-template-service-broker\n    openshift-web-console\n\nUsing project \"myproject\".\nNow using project \"ansible-service-broker\" on server \"https://10.201.82.163:8443\".\n\nYou can add applications to this project with the 'new-app' command. For example, try:\n\n    oc new-app centos/ruby-22-centos7~https://github.com/openshift/ruby-ex.git\n\nto build a new example application in Ruby.\nservice \"asb\" created\nservice \"asb-etcd\" created\nserviceaccount \"asb\" created\nclusterrolebinding \"asb\" created\nclusterrole \"asb-auth\" created\nclusterrolebinding \"asb-auth-bind\" created\nclusterrole \"access-asb-role\" created\npersistentvolumeclaim \"etcd\" created\ndeploymentconfig \"asb\" created\ndeploymentconfig \"asb-etcd\" created\nsecret \"asb-auth-secret\" created\nsecret \"registry-auth-secret\" created\nsecret \"etcd-auth-secret\" created\nsecret \"broker-etcd-auth-secret\" created\nconfigmap \"broker-config\" created\nserviceaccount \"ansibleservicebroker-client\" created\nclusterrolebinding \"ansibleservicebroker-client\" created\nsecret \"ansibleservicebroker-client\" created\nroute \"asb-1338\" created\nunexpected exit of OpenShift Ansible Broker (OAB) installation script", "stdout_lines": ["starting install of OpenShift Ansible Broker (OAB)", "Logged into \"https://10.201.82.163:8443\" as \"system:admin\" using existing credentials.", "", "You have access to the following projects and can switch between them with 'oc project <projectname>':", "", "    default", "    kube-public", "    kube-service-catalog", "    kube-system", "  * myproject", "    openshift", "    openshift-infra", "    openshift-node", "    openshift-template-service-broker", "    openshift-web-console", "", "Using project \"myproject\".", "Now using project \"ansible-service-broker\" on server \"https://10.201.82.163:8443\".", "", "You can add applications to this project with the 'new-app' command. For example, try:", "", "    oc new-app centos/ruby-22-centos7~https://github.com/openshift/ruby-ex.git", "", "to build a new example application in Ruby.", "service \"asb\" created", "service \"asb-etcd\" created", "serviceaccount \"asb\" created", "clusterrolebinding \"asb\" created", "clusterrole \"asb-auth\" created", "clusterrolebinding \"asb-auth-bind\" created", "clusterrole \"access-asb-role\" created", "persistentvolumeclaim \"etcd\" created", "deploymentconfig \"asb\" created", "deploymentconfig \"asb-etcd\" created", "secret \"asb-auth-secret\" created", "secret \"registry-auth-secret\" created", "secret \"etcd-auth-secret\" created", "secret \"broker-etcd-auth-secret\" created", "configmap \"broker-config\" created", "serviceaccount \"ansibleservicebroker-client\" created", "clusterrolebinding \"ansibleservicebroker-client\" created", "secret \"ansibleservicebroker-client\" created", "route \"asb-1338\" created", "unexpected exit of OpenShift Ansible Broker (OAB) installation script"]}
	to retry, use: --limit @/home/redhat/mobile-core/installer/playbook.retry

**Comment by finp** [comment]
if still a problem , open an issue on mobile-core
