### ISSUE TITLE
getting started - Running the Mobile App in an Emulator - copy mobile-services.json file to app directory on iOS unclear

### ISSUE THREAD

**Issue by mmurphy** [aerogear/mobile-docs#273]
The instruction to copy the mobile-services.json file to the iOS app directory is not clear.
the directory is not the top level ios-showcase-template directory that was cloned, but is the ios-showcase-template/ios-showcase-template directory which already has an existing mobile-services.json

**Comment by jstaffor** [comment]
@mmurphy - Does this comment match the change your expected as per your comment: https://github.com/aerogear/mobile-docs/pull/291 ?

**Comment by finp** [comment]
@wtrocki  can we discuss this ? make it a uniform experience for user

**Comment by finp** [comment]
docs change tracked in https://github.com/aerogear/mobile-docs/issues/303
