### ISSUE TITLE
Getting Started - iOS - No Pod Install on getting started guide

### ISSUE THREAD

**Issue by davidffrench** [aerogear/mobile-docs#275]
The showcase app section lists that `pod install` needs to be run - https://docs.aerogear.org/aerogear/latest/showcase-apps.html#build but the getting started guide does not - https://docs.aerogear.org/aerogear/latest/getting-started.html#running-the-mobile-app-in-an-emulator

The XCode build fails due to pod install not running.

**Comment by finp** [comment]
fixed in #297
