### ISSUE TITLE
Add note to mobile-services.json location for iOS

### ISSUE THREAD

**Issue by finp** [aerogear/mobile-docs#303]
## Description
In iOS dev env, dropping a file to a location is not sufficient, you must also add it to xcode.
However, users may already have done this, or be using showcase app, where this extra step is unnecessary

## Change
from 

Locate this file at the following location in your application project:

<app directory>/mobile-services.json

to 

Locate this file at the following location in your application project:

<app directory>/mobile-services.json

NOTE: Make sure this file is visible in Xcode, add the file if necessary.

**Comment by jstaffor** [comment]
I assumed that the change applied to the iOS part of the content given "In iOS dev env, " comment above. I was slightly confused though as the the content contains "`<app directory>/mobile-services.json`", not "/mobile-services.json". 

@finp - can you confirm that this is correct as per your comment above: https://github.com/aerogear/mobile-docs/pull/309

**Comment by finp** [comment]
PR looks good, just need to sort commit history and we can merge, and close this issue
