### ISSUE TITLE
Xamarin Dev not supported for windows  apps

### ISSUE THREAD

**Issue by finp** [aerogear/mobile-docs#317]
When creating user docs for xamarin sdk, it's important that we set expectations, Windows is not supported, so need something like:
NOTE: You can only use the AeroGear Xamarin SDK to create iOS and Android Apps.

**Comment by finp** [comment]
suggested location: https://docs.aerogear.org/aerogear/latest/getting-started.html#supported-environments

**Comment by jstaffor** [comment]
https://github.com/aerogear/mobile-docs/pull/337
