### ISSUE TITLE
bad link to certificate pinning

### ISSUE THREAD

**Issue by finp** [aerogear/mobile-docs#322]
## Description
link to certificate pinning is dead. links to 

## Link to Page/Section where Issue was seen
https://docs.aerogear.org/aerogear/latest/mobile-clients.html#android

## Suggested edit
link to https://docs.aerogear.org/aerogear/latest/device-security.html#cert-pinning
(using proper syntax)

**Comment by jstaffor** [comment]
@finp  - ready fir review: https://github.com/aerogear/mobile-docs/pull/341

**Comment by jstaffor** [comment]
https://github.com/aerogear/mobile-docs/pull/341
