### ISSUE TITLE
[push] 404 links on push page

### ISSUE THREAD

**Issue by finp** [aerogear/mobile-docs#323]
## Description
bad links on https://docs.aerogear.org/aerogear/latest/push-notifications.html
*  See Firebase Setup
*  See Google setup

**Comment by pmacko1** [comment]
https://docs.aerogear.org/aerogear/push-notifications.html#proc_preparing-ups-for-use-with-ios_preparing-ups-for-use-with-ios is 404 as well, i suspect there will be more

**Comment by pmacko1** [comment]
is firebase working for iOS as well? @jhellar @psturc try to tag somebody, pls

**Comment by pmacko1** [comment]
https://github.com/aerogear/mobile-docs/pull/540
