### ISSUE TITLE
Add documentation about installing mobile services on an existing cluster

### ISSUE THREAD

**Issue by finp** [aerogear/mobile-docs#325]
https://github.com/aerogear/mobile-core/blob/master/docs/walkthroughs/setup-mobile-on-existing-cluster.adoc

**Comment by pmacko1** [comment]
https://github.com/aerogear/mobile-core/pull/125 might this be related?

**Comment by pmacko1** [comment]
will we still be supporting this?

**Comment by finp** [comment]
@pmacko1  good point
