### ISSUE TITLE
Formatting Issues

### ISSUE THREAD

**Issue by laurafitzgerald** [aerogear/mobile-docs#347]
## Description
There is a formatting issue [here](https://docs.aerogear.org/aerogear/latest/getting-started.html#running-the-app-in-an-emulator)

## Link to Page/Section where Issue was seen
https://docs.aerogear.org/aerogear/latest/getting-started.html#running-the-app-in-an-emulator

## Suggested edit
Remove note which is causing the formatting issue

**Comment by pmacko1** [comment]
https://github.com/aerogear/mobile-docs/pull/348
