### ISSUE TITLE
[proposal] mini review "Downloading the Mobile Services Configuration File" procedure

### ISSUE THREAD

**Issue by pmacko1** [aerogear/mobile-docs#355]
## Description
```
4. Save the contents of the clipboard to a new file called mobile-services.json.

NOTE: The mobile-services.json file is the link between your provisioned  services on OpenShift and the mobile app you are developing. This file provides all required configuration to initialise the various SDKs and  get them hooked up/connected to the back-end services.

5. Follow the next specific additional instructions depending on your platform:

```
## Link to Page/Section where Issue was seen
identity-management.html#downloading-the-mobile-services-configuration-file

## Suggested edit
Make it a one step. There is a table under the `5.` with instructions where to put `mobile-services.json` specific to different platforms.
OR
`5. Save mobile-services.json to a specific location corresponding to a platform. Refer to this table:`
or similar

**Comment by finp** [comment]
@pmacko1  not sure what you mean by one step?

I think the colon leads the reader to the table, without specifically mentioning 'table', but if you have another suggestion?

**Comment by pmacko1** [comment]
@finp yep it is not clear if you don't see the text 
![image](https://user-images.githubusercontent.com/25327687/44520472-35c03f00-a6d0-11e8-8596-3f16483ced84.png)

You get the info you need from those steps, so i presume this is an ultra low priority/isn't an issue
