### ISSUE TITLE
[getting started] add prereq for internet connection?

### ISSUE THREAD

**Issue by pmacko1** [aerogear/mobile-docs#365]
## Description
Might be suggested already by a prereq for a Dockerhub account. Dev might want to deploy local dev environment offline with downloaded mobile-core repo. WDYT?

suggested edit: https://github.com/aerogear/mobile-docs/pull/366

**Comment by pmacko1** [comment]
https://github.com/aerogear/mobile-docs/pull/366

**Comment by finp** [comment]
@pmacko1  if we have a prereq for dockerhub and expect users to understand what that means, does it make sense to add this requirement?

**Comment by pmacko1** [comment]
`Access to a Docker Hub account. The installer uses Docker Hub as a source for AeroGear Docker images.
` yep makes sense
