### ISSUE TITLE
[getting started] improve "Registering a mobile client", what is the name of showcase app?

### ISSUE THREAD

**Issue by pmacko1** [aerogear/mobile-docs#376]
## Description
`On the wizard’s configuration screen, it is recommended that you input the name of the showcase application into the Package Name text box.`

## Link to Page/Section where Issue was seen
Getting Started>Registering a Mobile Client

## Suggested edit
Put table with showcase apps' names there

**Comment by pmacko1** [comment]
@danielpassos Hi, could you confirm, that `com.aerogear.androidshowcase`  is the name for android showcase app? Thanks!

**Comment by danielpassos** [comment]
@pmacko1 Unfortunately yes. It should be `org.aerogear` but for some reason it's using `com.aerogear`

See: https://github.com/aerogear/android-showcase-template/blob/master/app/build.gradle#L9
