### ISSUE TITLE
[getting started] update local development env setup android

### ISSUE THREAD

**Issue by pmacko1** [aerogear/mobile-docs#379]
## Description
from https://developer.android.com/studio/intro/studio-config

```Set the JDK version
A copy of the latest OpenJDK comes bundled with Android Studio 2.2 and higher, and this is the JDK version we recommend you use for your Android projects.
```

## Link to Page/Section where Issue was seen
https://docs.aerogear.org/aerogear/latest/getting-started.html#supported-environments

## Suggested edit
Remove 
`(Recommended) The latest version of OpenJDK`

**Comment by pmacko1** [comment]
@danielpassos ?

**Comment by danielpassos** [comment]
IMHO we should not have this section on the website. If you are going to make an app on whatever platform you should know what is the pre req

**Comment by pmacko1** [comment]
https://github.com/aerogear/mobile-docs/issues/256
