### ISSUE TITLE
[getting started] build android app update

### ISSUE THREAD

**Issue by pmacko1** [aerogear/mobile-docs#380]
## Description
I only have android studio installed, no gradlew, idk if it is a standard ?

## Link to Page/Section where Issue was seen
https://docs.aerogear.org/aerogear/latest/getting-started.html#building-the-app

## Suggested edit
make it ambiguous -> use whatever tool you are using to build android apps wdyt @danielpassos ?

**Comment by danielpassos** [comment]
The website is correct. When you create an Android project it auto create a `gradlew` file in your project. 

See: https://github.com/aerogear/android-showcase-template/

**Comment by pmacko1** [comment]
thanks, TIL ! I will update the docs (maybe unnecessarily for android dev) that `cd to root` wdyt?

**Comment by danielpassos** [comment]
IMHO, we should not provide any of that info. If you are not an Android developer you should visit the Android website first. All of this info is already there provided and updated from Google. Why are we duplicating it?

https://developer.android.com/training/basics/firstapp/
https://developer.android.com/studio/build/building-cmdline
