### ISSUE TITLE
[generic] add prereqs to Binding a Mobile Client

### ISSUE THREAD

**Issue by pmacko1** [aerogear/mobile-docs#399]
## Description
you need a mobile client in order to be able to  bind it

## Suggested edit
edit generic-binding.adoc

**Comment by pmacko1** [comment]
https://github.com/aerogear/mobile-docs/pull/418

**Comment by finp** [comment]
I think we had prereqs in 'binding' and we were asked to remove them, given the context, it was obvious what you need

**Comment by pmacko1** [comment]
Binding a Mobile Client - well you need a Mobile Client. I think I just followed a comment in gdoc, closing
