### ISSUE TITLE
[binding] document what is Mobile client ID/Service ID

### ISSUE THREAD

**Issue by pmacko1** [aerogear/mobile-docs#405]
## Description
You can create binding by several ways
1. from mobile client (this fills the Mobile client ID/Service ID)
2. from service (this leaves Mobile client ID/Service ID empty)

Now we point users to use 1.

**Comment by pmacko1** [comment]
@jhellar any idea?

**Comment by jhellar** [comment]
@pmacko1 couldn't find docs mentioning mobile client id, can you send a link where this is mentioned?

**Comment by pmacko1** [comment]
@jhellar that's the catch ;)

**Comment by pmacko1** [comment]
this has been outdated by integrating mobile developer console i presume @jhellar ?

**Comment by jhellar** [comment]
@pmacko1 yes, I think that with MDC, we want users to only create bindings via MDC. Closing this issue.
