### ISSUE TITLE
[keycloak, cordova] change redirect uri

### ISSUE THREAD

**Issue by pmacko1** [aerogear/mobile-docs#410]
## Description
from @pawelpaszki 
`Add <schema>:/callback to Valid Redirect URIs.`
```
this is wrong for cordova and will result in 'wrong redirect params' being displayed. The valid Redirect URI should be just:

http://localhost/*
```
## Link to Page/Section where Issue was seen
https://docs.aerogear.org/aerogear/latest/getting-started.html#configuring-keycloak

## Suggested edit
Add note with valid URI for cordova

**Comment by finp** [comment]
I believe the reason for the existing doc structure is due to an issue with using 'tabs' in numbered lists. I suggest  a PR that brings the 'tabs' into the 'procedure'.

**Comment by pmacko1** [comment]
ok, i'm gonna fix this and close this issue

**Comment by pmacko1** [comment]
@finp to a procedure here https://docs.aerogear.org/aerogear/latest/getting-started.html#binding ? I do not think that it might fit there, wdyt
