### ISSUE TITLE
[xamarin, implement auth] fix method name

### ISSUE THREAD

**Issue by pmacko1** [aerogear/mobile-docs#414]
## Description
https://docs.aerogear.org/aerogear/latest/identity-management.html#implementing-authentication
## Suggested edit
`IAuthService authService = MobileCore.Instance.GetInstance<IAuthService>();`
->
`IAuthService authService = MobileCore.Instance.GetService<IAuthService>();`
https://docs.google.com/document/d/12XpvIlzY1baNKVyj_oMiXK_-Vi7iN-qGD2OPrTCZ2ko/edit#
@jhellar

**Comment by pmacko1** [comment]
@jhellar I think multiple snippets have this error, could you check pls?

**Comment by jhellar** [comment]
@pmacko1 yes, this error is in more snippets. All places with this error should be commented in the google document.
