### ISSUE TITLE
[mobile-services.json, legacy xamarin-android] incorrect mobile-services.json location

### ISSUE THREAD

**Issue by pmacko1** [aerogear/mobile-docs#424]
## Description
```
Xamarin
Locate this file at the following location in your application project:
Resources/mobile-services.json
```
from @jhellar 
```
This is true for Xamarin Foms app. For Legacy Xamarin for Android, it should be in Assets folder. Not sure about Legacy Xamarin for iOS.

Also in case of Xamarin Forms app, user needs to right click on the mobile-services.json file, open Properties, and change Build Action field to "EmbeddedResource".
```

What is the difference between `Xamarin Forms` and `Legacy Xamarin` ? Was there a `Legacy Xamarin Forms` ?
## Link to Page/Section where Issue was seen
modules/ROOT/pages/_partials/generic-obtaining-the-mobile-sdk-config-file.adoc

## Suggested edit
?

**Comment by jhellar** [comment]
@wojta can you help here, with the Legacy Xamarin for iOS?

**Comment by wojta** [comment]
Xamarin.Forms  app expects shared `Resources` directory.  Legacy Android uses `Assets`. Legacy iOS also directory called `Resources`. There must be proper build action set for these directories, so they are processed as proper for their platforms. 
Platform specific code:
`https://github.com/aerogear/aerogear-xamarin-sdk/blob/master/Core/Core.Platform.Android/AndroidPlatformInjector.cs`
`https://github.com/aerogear/aerogear-xamarin-sdk/blob/master/Core/Core.Platform.iOS/IOSPlatformInjector.cs`

**Comment by finp** [comment]
@wojta can you give me any links for Xamarin Legacy? 
was there a point in time (version) where Xamarin changed?
