### ISSUE TITLE
[metrics] fix left hand menu - Remove Device Trust 

### ISSUE THREAD

**Issue by pmacko1** [aerogear/mobile-docs#446]
## Description
https://docs.aerogear.org/aerogear/latest/mobile-metrics.html

## Link to Page/Section where Issue was seen
left hand menu

## Suggested edit
remove `*** xref:mobile-metrics.adoc#setup[Device Trust]` from `nav.adoc`

**Comment by pmacko1** [comment]
Idk if we should remove it or link to proc_performing-device-checks @jhellar could you look into this? Thanks.

**Comment by jhellar** [comment]
@pmacko1 I would say remove it, as it is not in metrics section.
