### ISSUE TITLE
change openshift requirement to 3.9 only

### ISSUE THREAD

**Issue by finp** [aerogear/mobile-docs#452]
In https://docs.aerogear.org/aerogear/latest/getting-started.html we say
Use OpenShift client tools version 3.9 or later
However, it should be 3.9 only, so remove 'or later'

ping @joaedwar

**Comment by pmacko1** [comment]
@finp there is 3.10 out now and it might/might not be supported in future? (there has to be a specific version of openshift installed(depends on docker version)). Now cluster_up_down.md only documents 3.9...

**Comment by finp** [comment]
3.10 doesn't work, asking @joaedwar to make this small change as part of onboarding,
