### ISSUE TITLE
remove unnecessary attributes.adoc includes

### ISSUE THREAD

**Issue by finp** [aerogear/mobile-docs#492]
To allow for reorg, we need to make sure that attributes.adoc is only included once per html page, currently many partials include this file.
include attributes.adoc only in top level file (12 apostles)

**Comment by pmacko1** [comment]
what about mobile security?

**Comment by finp** [comment]
ignore mob security, assume that for any issues, unless it's specifically mentioned

**Comment by pmacko1** [comment]
:ok:

**Comment by pmacko1** [comment]
if i removed the include from _partials, diff reports no changes in htmls

**Comment by pmacko1** [comment]
if i removed the includes from the subfolders, some of the apostles decided to cause havok.
i.e. parameters/variables/whatever the placeholders are called are unresolved. 

It can be because we render the htmls separately and then link them together?

**Comment by finp** [comment]
@pmacko1  One possible workaround for this would be to try:
1. move all subfolders, eg sync, to _partials
2. change all includes in apostles to include::_partials/<existing-path>
3. test
4. remove include::attributes.adoc
5. test again

**Comment by pmacko1** [comment]
13 apostles actually
* xref:getting-started.adoc[Getting Started]
* xref:mobile-developer-console.adoc[Mobile Developer Console]
* xref:con_services.adoc[Mobile Services]
** xref:identity-management.adoc[{keycloak-service}]

** xref:push-notifications.adoc[{unifiedpush-service}]
** xref:mobile-metrics.adoc[{metrics-service}]
** xref:mobile-cicd.adoc[{mobile-ci-cd-service}]
** xref:data-sync.adoc[{sync-service}]

** xref:device-security.adoc[{device-security-service}]
* xref:showcase-apps.adoc[Showcase Apps]
* xref:ref_api.adoc[API Reference]
* xref:mobile-cli.adoc[Mobile CLI]

* xref:glossary.adoc[Glossary]

**Comment by pmacko1** [comment]
stuck, couldn't render docs properly if i removed `include::attributes.adoc` from docs in _partials

**Comment by finp** [comment]
I think the issues you encountered were due to errors at the start of each master assembly file (apostle).
See #512  I believe this works
