### ISSUE TITLE
what are tags and why do we use it in documentation?

### ISSUE THREAD

**Issue by pmacko1** [aerogear/mobile-docs#495]
## Description
example: `modules/ROOT/pages/getting-started.adoc`
include::{partialsdir}/build-and-deploy.adoc[tags=build]

Can be a part of documentation of doc workflow.

**Comment by finp** [comment]
tags are a method to include partial files in adoc. Normally used to include code snippets, but can be used to 'query docs', eg I write build and deploy doc for a user story, but want to include only part of that adoc in my other user story, this is the method I use:
1. tag the piece i want to include
2. include only that part
