### ISSUE TITLE
runtime connector(custom) move to unpublished or delete the adocs

### ISSUE THREAD

**Issue by pmacko1** [aerogear/mobile-docs#498]
## Description
ssia, unpublished, runtime connector has been deprecated, do we need to archive these docs? @finp

**Comment by finp** [comment]
I've created https://github.com/aerogear/mobile-docs/releases/tag/runtime-connector so lets remove the runtime connector docs and we can always retrieve them afterwards using this tag

**Comment by pmacko1** [comment]
wouldn't be `runtime-connector-deprecation` better?

**Comment by finp** [comment]
possibly, will keep in mind next time
