### ISSUE TITLE
[device security] include glossary in device-security.adoc

### ISSUE THREAD

**Issue by pmacko1** [aerogear/mobile-docs#524]
pls approve @finp

**Comment by finp** [comment]
1. Should there be a glossary section included at the top of device security master assembly file?
2. There seems to be a heading missing from https://docs.aerogear.org/aerogear/latest/glossary.html for security

**Comment by pmacko1** [comment]
should there be a glossary in any master file?
2. fixed in #526

**Comment by pmacko1** [comment]
also this is only a `blind` fix of a broken xref.

**Comment by pmacko1** [comment]
oh, this is also fixed in #526

**Comment by finp** [comment]
@pmacko1  I think we'll continue to have a glossary section for each master.
so there's an issue that there isn't one in device security master.

Can we close this issue and/or create a new issue to tackle that

**Comment by pmacko1** [comment]
@finp there isn't a glossary in any of the masters

**Comment by finp** [comment]
I mean terminology section, like https://docs.aerogear.org/aerogear/latest/identity-management.html#ref_terminology_Identity%20Management_ref_terminology

**Comment by pmacko1** [comment]
i would merge this, because it keeps the original text and raise an issue if there should be glossaries included in the masters wdyt

**Comment by finp** [comment]
@pmacko1  yes, i agree
issue is that we have terminology section in each service master, except device security

**Comment by pmacko1** [comment]
yeah, i see that now. motivation to duplicate the glossaries?

also the device security is different right, it is not a "copy"

**Comment by pmacko1** [comment]
or, this issue is called add xref to glossary, why open a new one, right
