### ISSUE TITLE
Replace current tab method with antora tab method

### ISSUE THREAD

**Issue by pmacko1** [aerogear/mobile-docs#534]
https://trello.com/c/FULhwuGm/65-replace-current-tab-method-with-antora-tab-method

**Comment by jstaffor** [comment]
I have completed a lot of work for this:

PRs for this work:
Tab work for files outside of the service's folders
#570 opened 5 hours ago by jstaffor • Review required  
Showcase-apps only tab work done for 'tabs' syntax. Building locally
#569 opened 2 days ago by jstaffor • Review required  
Sync only tab work done for 'tabs' syntax. Building locally
#568 opened 2 days ago by jstaffor • Review required  
Security only tab work done for 'tabs' syntax. Building locally
#567 opened 2 days ago by jstaffor • Review required  
Metrics only tab work done for 'tabs' syntax
https://github.com/aerogear/mobile-docs/pulls
