### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by austincunningham** [aerogear/mobile-docs#549]
## Description
missing images 
![image](https://user-images.githubusercontent.com/16667688/49868736-3d822b80-fe06-11e8-9d1c-b787c80bc5af.png)

## Expected Behavior
images should be present 

## Actual Behavior
see screen shot

## Steps to reproduce
- open link https://docs.aerogear.org/aerogear/latest/getting-started.html#provisioning browse to images

**Comment by pmacko1** [comment]
hi @austincunningham , i can see them in firefox 64, fedora 29. could you re-check pls and close if ok? Thanks

**Comment by austincunningham** [comment]
@pmacko1 images look to be back , closing the issue
