### ISSUE TITLE
tag 1.0.0 doesn't exist

### ISSUE THREAD

**Issue by austincunningham** [aerogear/mobile-docs#550]
## Description
the tag 1.0.0 that is outlined here 

![image](https://user-images.githubusercontent.com/16667688/49869186-8f778100-fe07-11e8-8750-e27232abde56.png)

doesn't exist, below are the tags that are present
```
$ git tag
0.0.1
1.0.0-alpha

```

## Expected Behavior
change the docs to point to 1.0.0-alpha

## Steps to reproduce
- Browse to https://docs.aerogear.org/aerogear/latest/getting-started.html#introduction

**Comment by pmacko1** [comment]
hi @austincunningham, could you please check again?
![image](https://user-images.githubusercontent.com/25327687/51393685-95642e80-1b38-11e9-81ec-2fc85ef9cbb0.png)

**Comment by austincunningham** [comment]
@pmacko1 I should have close this some time ago the tag was added the following day

**Comment by pmacko1** [comment]
no bother
