### ISSUE TITLE
The cordova workflow seems to be instructions for ionic

### ISSUE THREAD

**Issue by austincunningham** [aerogear/mobile-docs#551]
## Description
The Cordova tab instructions seem to be for an ionic app
![image](https://user-images.githubusercontent.com/16667688/49880504-39650680-fe24-11e8-9eff-861a230c74b6.png)
cordova apps don't have a src directory but ionic apps do, ionic:build is a ionic command, The  redirects schema doens't work for a cordova app but does work for an ionic app.  

## Expected Behavior
believe the tab should read ionic rather that cordova,

## Steps to reproduce
build a cordova app
```
install -g cordova
cordova create app
cd app
cordova platform add browser
cordova run browser
```
follow the steps outline https://docs.aerogear.org/aerogear/latest/identity-management.html for cordova

**Comment by finp** [comment]
@pmacko1  think we can close this?

**Comment by pmacko1** [comment]
it is still for Ionic I believe. Ionic being built upon Cordova, i don't know. @austincunningham ?

**Comment by austincunningham** [comment]
@pmacko1 , @finp , I suppose the technology is cordova, the instructions are for the ionic framework which is build on cordova. Showcase app is ionic as well

**Comment by pmacko1** [comment]
questions (i know nothing about dev with cordova)
- are all snippets across docs repo for ionic? -> if true, we should document this
- do we expect users to use ionic with cordova? if not, we should rewrite snippets to cordova
- what should we do if question1 == true ?

**Comment by austincunningham** [comment]
UPS seems to have both ionic and cordova called out see https://docs.aerogear.org/aerogear/latest/push-notifications.html#downloading-the-mobile-services-configuration-file, may just be worth change the tab name to `ionic/cordova`

**Comment by finp** [comment]
@wei-lee is this something we want to do? If so, we should be consistent across all services

**Comment by wei-lee** [comment]
@finp It is a tricky one, most of the time I believe we can share the same code between cordova and ionic, there are a few cases there are small difference between the 2 and we need to call them out. So the correct way is to change it to `Ionic`, however, my concern is that people will feel it is not cordova and they will then think we don't support cordova.

So maybe we add tabs for both?

**Comment by austincunningham** [comment]
:+1:  On two tabs

**Comment by finp** [comment]
we've changed this for showcase app, and it seems that we won't change it for rest of docs, reopen if required.
