### ISSUE TITLE
missing or incorrect steps on creating a binding 

### ISSUE THREAD

**Issue by austincunningham** [aerogear/mobile-docs#552]
## Description
The steps outline here https://docs.aerogear.org/aerogear/latest/identity-management.html#binding-a-mobile-app-with-the-identity-management-service don't appear to match the steps required
![image](https://user-images.githubusercontent.com/16667688/49881886-43d4cf80-fe27-11e8-9cd8-4c6a1d9dcda4.png)

## Expected Behavior
bold are the changes to match the behavior

- Navigate to the Overview of your OpenShift project.
- **Click on the url for your mdc-server**
- Select the Mobile App name listed in the Mobile Apps section.
- Navigate to Mobile Services tab.
- Click **Bind to app button**  and follow the Create Binding wizard to associate the Mobile App with the Identity Management Service.

## Actual Behavior
![image](https://user-images.githubusercontent.com/16667688/49881886-43d4cf80-fe27-11e8-9cd8-4c6a1d9dcda4.png)

## Steps to reproduce
follow the instructions layed out at https://docs.aerogear.org/aerogear/latest/identity-management.html#binding-a-mobile-app-with-the-identity-management-service

**Comment by finp** [comment]
out of date: https://mobile-docs.netlify.com/aerogear/latest/identity-management/#binding-an-app-to-idm
