### ISSUE TITLE
redirect uri not working for ionic cordova android build

### ISSUE THREAD

**Issue by austincunningham** [aerogear/mobile-docs#592]
## Description
redirect uri not working for cordova android build

## Expected Behavior
apk should have the same behavior as ionic serve

## Actual Behavior
I tested setting up a openshift cluster with the MDC and IDM and can get the ionic web app to work on my pc but when I build it with
```
ionic cordova build android
```
and upload the apk to the device it there is an issue with the redirect url on the mobile browser

We're Sorry ... Invalid parameter:redirect_uri

The redirect uri was set as follows

![image](https://user-images.githubusercontent.com/16667688/52052762-575f0580-254f-11e9-942b-f3e073fc5b9b.png)

## Environment

* Operating system: mint 18
* OpenShift versions: 3.11
* Project Versions: 1.0.0

## Steps to reproduce
Did some testing and change the redirect uri to * to accept any input and this was a successful connection url on the mobile device

https://keycloak-e05b0d-test-project.apps.waterford-b3be.openshiftworkshop.com/auth/realms/test-project/protocol/openid-connect/auth?client_id=test-ionic-public&redirect_uri=http%3A%2F%2Flocalhost&state=6c240927-bc64-46ee-91b4-3bb64227701a&response_mode=fragment&response_type=code&scope=openid&nonce=ebc7ba3a-89be-49b6-8009-c08552db276d

I can see that the successful redirect uri is 
**redirect_uri=http%3A%2F%2Flocalhost**
which would be http://localhost

Tested on android with the redirect_uri set to http://localhost and I get the login screen.

Looks like the redirect uri needs to be documented differently

**Comment by finp** [comment]
@austincunningham  @wei-lee  I'm not sure what update is required:
* cordova redirect URIs (currently we ask users to enter package name)
* ionic cordova redirect URIs

Finally, are there knock on effects wrt Web Origins values?

**Comment by wei-lee** [comment]
@finp We are trying out an updated plugin to do auth for cordova & ionic, hopefully it will make things simpler. Will send a PR to the docs once we verified it is working.

**Comment by austincunningham** [comment]
@finp referring to this section of the docs

![image](https://user-images.githubusercontent.com/16667688/52203683-cdbe7900-2869-11e9-9845-ce8a8336c82e.png)

**Comment by austincunningham** [comment]
@finp Correct, my mistake should have include the docs link image originally

**Comment by finp** [comment]
changes made, can be seen at https://mobile-docs.netlify.com/aerogear/latest/identity-management/#configuring-idm
