### ISSUE TITLE
cordova tab duplicated

### ISSUE THREAD

**Issue by austincunningham** [aerogear/mobile-docs#670]
## Description
cordova tab is duplicated here https://docs.aerogear.org/aerogear/latest/device-security.html#downloading-the-mobile-services-configuration-file

## Expected Behavior
should only be here once 

## Actual Behavior
cordova tab appears twice 

![image](https://user-images.githubusercontent.com/16667688/55241438-f4c67500-5232-11e9-8f2e-02cb27c85dbe.png)

## Environment
N/A
## Steps to reproduce
- click on the link https://docs.aerogear.org/aerogear/latest/device-security.html#downloading-the-mobile-services-configuration-file
- look at the tab section

**Comment by briandooley** [comment]
@austincunningham Just checked this and it appears to be resolved.  Not seeing Cordova twice at all.

**Comment by austincunningham** [comment]
yea fine
